/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/base/BaseButton.vue')['default']
    BaseCard: typeof import('./src/components/base/BaseCard.vue')['default']
    BaseInput: typeof import('./src/components/base/BaseInput.vue')['default']
    BaseModal: typeof import('./src/components/base/BaseModal.vue')['default']
    BaseSelect: typeof import('./src/components/base/BaseSelect.vue')['default']
    BaseTable: typeof import('./src/components/base/BaseTable.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
